name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - matplotlib
  - numpy < 2.3.0 # sympy 1.12 requires below numpy 2.3.0
  - scipy
  - sympy = 1.12
  - xeus-python
